eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    healthcheck:
      enabled: true

spring:
  application:
    name: ${CARD_SERVICE_NAME:card-payment-service}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:psp-card-payment}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode: always
  zipkin:
    baseUrl: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/
  sleuth:
    sampler:
      probability: 1

server:
  port: ${CARD_SERVICE_PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

service:
  bank1:
    url: http://${BANK1_HOST:localhost}:${BANK1_PORT:8061}
  bank2:
    url: http://${BANK2_HOST:localhost}:${BANK2_PORT:8062}
  payment-request:
    name: ${PAYMENT_REQUEST_SERVICE_NAME:payment-request-service}
  gateway:
    name: ${GATEWAY_NAME:gateway}