eureka:
  client:
    serviceUrl:
      defaultZone: https://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    healthcheck:
      enabled: true
  instance:
    secure-port-enabled: true
    non-secure-port-enabled: false
    hostname: ${EUREKA_HOST:localhost}

spring:
  application:
    name: ${CARD_SERVICE_NAME:card-payment-service}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DBB_NAME:psp-card-payment}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode: always
  zipkin:
    baseUrl: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/
  sleuth:
    sampler:
      probability: 1

server:
  port: ${CARD_SERVICE_PORT:8080}
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:card-payment-service.keystore.p12
    key-store-password: password
    key-alias: card-payment-service
    trust-store: classpath:truststore.p12
    trust-store-password: password
    trust-store-type: PKCS12
  error:
    include-message: always
    include-binding-errors: always
  address: 0.0.0.0

service:
  bank1:
    url: https://${BANK1_HOST:localhost}:${BANK1_PORT:8061}
  bank2:
    url: https://${BANK2_HOST:localhost}:${BANK2_PORT:8062}
  payment-request:
    name: ${PAYMENT_REQUEST_SERVICE_NAME:payment-request-service}
  gateway:
    address: ${GATEWAY_ADDRESS:https://localhost:8090}
  auth:
    name: ${AUTH_SERVICE_NAME:auth-service}
  store:
    name: ${STORE_SERVICE_NAME:store-service}

encryption:
  keystore-name: ${ENCRYPTION_KEYSTORE_NAME:D:\\enc\\encryption.p12}
  keystore-password: ${ENCRYPTION_KEYSTORE_PASSWORD:password}
  keystore-entry-name: ${ENCRYPTION_KEYSTORE_ENTRY_NAME:key}
  keystore-entry-password: ${ENCRYPTION_KEYSTORE_ENTRY_PASSWORD:password}