eureka:
  client:
    serviceUrl:
      defaultZone: https://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 2
  instance:
    secure-port-enabled: true
    non-secure-port-enabled: false
    hostname: ${EUREKA_HOST:localhost}

spring:
  application:
    name: ${GATEWAY_NAME:gateway}
  zipkin:
    baseUrl: https://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/
  sleuth:
    sampler:
      probability: 1
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: store-service
          uri: lb://${STORE_SERVICE_NAME:store-service}
          predicates:
            - Path=/store/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: lb://${AUTH_SERVICE_NAME:auth-service}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: card-payment-service
          uri: lb://${CARD_SERVICE_NAME:card-payment-service}
          predicates:
            - Path=/card/**
          filters:
            - StripPrefix=1
        - id: payment-request-service
          uri: lb://${PAYMENT_REQUEST_SERVICE_NAME:payment-request-service}
          predicates:
            - Path=/request/**
          filters:
            - StripPrefix=1
        - id: bitcoin-payment-service
          uri: lb://${BITCOIN_SERVICE_NAME:bitcoin-payment-service}
          predicates:
            - Path=/bitcoin/**
          filters:
            - StripPrefix=1
        - id: paypal-payment-service
          uri: lb://${PAYPAL_SERVICE_NAME:paypal-payment-service}
          predicates:
            - Path=/paypal/**
          filters:
            - StripPrefix=1
        - id: qrcode-payment-service
          uri: lb://${QRCODE_SERVICE_NAME:qrcode-payment-service}
          predicates:
            - Path=/qrcode/**
          filters:
            - StripPrefix=1

server:
  port: ${GATEWAY_PORT:8090}
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:gateway.keystore.p12
    key-store-password: password
    key-alias: gateway
    trust-store: classpath:truststore.p12
    trust-store-password: password
    trust-store-type: PKCS12