eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: false
    registry-fetch-interval-seconds: 2

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: store-service
          uri: lb://store-service
          predicates:
            - Path=/store/**
          filters:
            - StripPrefix=1
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: card-payment-service
          uri: lb://card-payment-service
          predicates:
            - Path=/card/**
          filters:
            - StripPrefix=1
        - id: payment-request-service
          uri: lb://payment-request-service
          predicates:
            - Path=/request/**
          filters:
            - StripPrefix=1

server:
  port: 8090