eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    healthcheck:
      enabled: true

spring:
  application:
    name: ${STORE_SERVICE_NAME:store-service}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/psp-store
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    generate-ddl: true
  sql:
    init:
      mode: always
  zipkin:
    baseUrl: http://${ZIPKIN_HOST:localhost}:${ZIPKIN_PORT:9411}/
  sleuth:
    sampler:
      probability: 1

server:
  port: ${STORE_SERVICE_PORT:8081}
  error:
    include-message: always
    include-binding-errors: always

service:
  auth:
    name: ${AUTH_SERVICE_NAME:auth-service}

token:
  secret: ${TOKEN_SECRET:5B43E507D1232852D06EEDD2E30A24F10ABC72AC114D60D6BB592A15BC505B8E}